{
  "route": {
    "enabled": true,
    "host": "connect-fourtkeh.example.com",
    "tls": {
      "enabled": true,
      "termination": "edge",
      "insecureEdgeTerminationPolicy": "Redirect"
    }
  }
}
